image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
    - step:
        name: Prepare ENV Variables
        script:
          - touch .env
          - echo DB_URL=$DB_URL > .env
          - echo DB_NAME=$DB_NAME >> .env
          - cat .env
    - step:
        name: Google App Engine
        deployment: Production          
        script:
        #- touch .env
        #- echo DB_URL=$DB_URL > .env
        #- echo DB_NAME=$DB_NAME >> .env
        #- cat .env
        - printf 'runtime:' >> app.yaml
        - printf ' python38' >> app.yaml
        - printf '\n' >> app.yaml
        - printf 'DB_URL:' >> app.yaml
        - printf ' $DB_URL' >> app.yaml
        - printf '\n' >> app.yaml
        - printf 'DB_NAME:' > app.yaml
        - printf ' $DB_NAME' > app.yaml
        - cat app.yaml
        - pipe: atlassian/google-app-engine-deploy:0.7.4
          variables:
            KEY_FILE: $KEY_FILE
            PROJECT: $PROJECT
            DB_URL: $DB_URL
            DB_NAME: $DB_NAME