image: python:3.7.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
    - step:
        name: Google App Engine
        script:
        - pipe: atlassian/google-app-engine-deploy:0.7.4
          variables:
            KEY_FILE: $KEY_FILE
            PROJECT: $PROJECT
    - step:
        name: Deploy to App Engine
        deployment: Test
        script:
            - echo $DB_URL
            - echo $DB_NAME