options:
  docker: true

  pipelines:
    default:
      - step:
          name: Deploy to Google Cloud Run
          deployment: Production        
          script:
          - pipe: atlassian/google-app-engine-deploy:0.7.4
            variables:
              KEY_FILE: $KEY_FILE
              PROJECT: $PROJECT