steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/appsbymatthew-api/appsbymatthew:latest', '.']
    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/appsbymatthew-api/appsbymatthew:latest']
    # Deploy container image to Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/appsbymatthew-api/appsbymatthew:latest', '--region', 'REGION', '--platform', 'managed']
    images:
    - gcr.io/appsbymatthew-api/appsbymatthew:latest